### ISSUE TITLE
Naming issue

### ISSUE THREAD

**Issue by kirillDanshin** [neelance/chanrpc#1]
Hi!
As I can see, chan**rcp**.go needs to be renamed to chan**rpc**.go.
Thanks!

**Comment by neelance** [comment]
Thanks for reporting!

**Comment by dmitshur** [comment]
This typo is also there in commit message of 7ec58d97dc0d7b89b5fc6504c29210e684e4c367, but fixing that is impossible. :)

**Comment by kirillDanshin** [comment]
@shurcooL hey, I can fix it but... is it necessary?

**Comment by dmitshur** [comment]
It's not possible to fix it without rewriting git history and force pushing `master`. It's not worth it. I just wanted to point that out.

**Comment by kirillDanshin** [comment]
@shurcooL It's was a joke ;)
